name: 'xero_integration_tests'
version: '0.3.1'
profile: 'integration_tests'
config-version: 2

vars: 
  xero_source:
    account: "{{ ref('xero_account_data') }}"
    journal_line: "{{ ref('xero_journal_line_data') }}"
    journal: "{{ ref('xero_journal_data') }}"
    contact: "{{ ref('xero_contact_data') }}"
    invoice: "{{ ref('xero_invoice_data') }}"
    invoice_line_item: "{{ ref('xero_invoice_line_item_data') }}"
    organization: "{{ ref('xero_organization_data') }}"
    credit_note: "{{ ref('xero_credit_note_data') }}"
    bank_transaction: "{{ ref('xero_bank_transaction_data') }}"

  xero:
    account: "{{ ref('stg_xero__account') }}" 
    contact: "{{ ref('stg_xero__contact') }}" 
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}" 
    invoice: "{{ ref('stg_xero__invoice') }}" 
    journal_line: "{{ ref('stg_xero__journal_line') }}" 
    journal: "{{ ref('stg_xero__journal') }}" 
    organization: "{{ ref('stg_xero__organization') }}" 